# Generated by Django 3.1.7 on 2021-03-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cusmtomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('cusLastname', models.CharField(max_length=100, null=True)),
                ('cusphone', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('cusLastname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='toto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('cusLastname', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('cusLastname', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
