# Generated by Django 3.1.7 on 2021-03-10 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210311_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.department'),
        ),
    ]
