# Generated by Django 3.1.7 on 2021-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_employee_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cusName',
            field=models.CharField(max_length=100, null=True, verbose_name='sami'),
        ),
    ]
