# Generated by Django 3.1.7 on 2021-03-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ditmDescription', models.CharField(max_length=100, null=True)),
                ('ditmQuantity', models.IntegerField(max_length=100, null=True)),
                ('ditmimagepath', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonationItemStatus', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonationType', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donrName', models.CharField(max_length=100, null=True)),
                ('donrAddress', models.CharField(max_length=150, null=True)),
                ('donrMobile', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonersType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DonersType', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDonationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDonationStatuse', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RequestDonation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.doners')),
                ('RequestDonationStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.requestdonationstatus')),
                ('donationItem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.donationitems')),
            ],
        ),
        migrations.AddField(
            model_name='doners',
            name='donrtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.donerstype'),
        ),
        migrations.AddField(
            model_name='donationitems',
            name='ditmDoner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.doners'),
        ),
        migrations.AddField(
            model_name='donationitems',
            name='ditmStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.donationitemstatus'),
        ),
        migrations.AddField(
            model_name='donationitems',
            name='ditmType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.donationtypes'),
        ),
    ]
