# Generated by Django 3.1.7 on 2021-03-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationitems',
            name='ditmQuantity',
            field=models.IntegerField(null=True),
        ),
    ]
